In [2]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import gradient_descent_v2
from keras.losses import categorical_crossentropy
from keras.metrics import accuracy
from keras.utils import to_categorical
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, roc_auc_score

2023-08-27 20:27:17.668637: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-27 20:27:17.853515: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-27 20:27:17.858382: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-08-27 20:27:17.858400: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore 

In [3]:
iris = load_iris()

In [4]:
data = iris.data
target = iris.target

In [5]:
cats = to_categorical(target)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(data, cats)
X_train

array([[6.7, 3. , 5. , 1.7],
       [5.7, 2.9, 4.2, 1.3],
       [5.4, 3. , 4.5, 1.5],
       [5. , 3.2, 1.2, 0.2],
       [7.6, 3. , 6.6, 2.1],
       [6.4, 3.2, 4.5, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [4.8, 3.1, 1.6, 0.2],
       [6. , 2.9, 4.5, 1.5],
       [5.6, 2.7, 4.2, 1.3],
       [4.9, 3.1, 1.5, 0.1],
       [6.4, 2.9, 4.3, 1.3],
       [6. , 2.2, 5. , 1.5],
       [5.5, 2.5, 4. , 1.3],
       [5.8, 2.8, 5.1, 2.4],
       [7.7, 2.8, 6.7, 2. ],
       [5.7, 2.6, 3.5, 1. ],
       [6.1, 2.6, 5.6, 1.4],
       [4.6, 3.2, 1.4, 0.2],
       [5. , 2. , 3.5, 1. ],
       [5.5, 2.6, 4.4, 1.2],
       [6.9, 3.1, 5.4, 2.1],
       [5.7, 2.8, 4.1, 1.3],
       [5.1, 3.7, 1.5, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [6. , 3.4, 4.5, 1.6],
       [5.7, 4.4, 1.5, 0.4],
       [5. , 3.5, 1.3, 0.3],
       [6.3, 2.3, 4.4, 1.3],
       [4.9, 3.6, 1.4, 0.1],
       [6. , 3. , 4.8, 1.8],
       [5.1, 3.8, 1.5, 0.3],
       [6.7, 3. , 5.2, 2.3],
       [6.9, 3

In [7]:
model = Sequential()
model.add(Dense(3, activation="sigmoid", input_shape=(4,)))

optimizer = gradient_descent_v2.SGD(learning_rate=0.01)
model.compile(optimizer=optimizer, metrics=accuracy, loss=categorical_crossentropy)
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


2023-08-27 20:27:20.488793: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-08-27 20:27:20.488821: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-08-27 20:27:20.488844: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (max-laptop): /proc/driver/nvidia/version does not exist
2023-08-27 20:27:20.489116: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [8]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=200)

Epoch 1/200
4/4 [==============================] - 1s 94ms/step - loss: 2.7902 - accuracy: 0.0000e+00 - val_loss: 1.5063 - val_accuracy: 0.0000e+00
Epoch 2/200
4/4 [==============================] - 0s 14ms/step - loss: 1.9823 - accuracy: 0.0000e+00 - val_loss: 1.4570 - val_accuracy: 0.0000e+00
Epoch 3/200
4/4 [==============================] - 0s 13ms/step - loss: 1.7486 - accuracy: 0.0000e+00 - val_loss: 1.4888 - val_accuracy: 0.0000e+00
Epoch 4/200
4/4 [==============================] - 0s 12ms/step - loss: 1.6712 - accuracy: 0.0000e+00 - val_loss: 1.4792 - val_accuracy: 0.0000e+00
Epoch 5/200
4/4 [==============================] - 0s 12ms/step - loss: 1.6184 - accuracy: 0.0000e+00 - val_loss: 1.4623 - val_accuracy: 0.0000e+00
Epoch 6/200
4/4 [==============================] - 0s 13ms/step - loss: 1.5658 - accuracy: 0.0000e+00 - val_loss: 1.4166 - val_accuracy: 0.0000e+00
Epoch 7/200
4/4 [==============================] - 0s 12ms/step - loss: 1.5224 - accuracy: 0.0000e+00 - val_loss

In [9]:
predictions = model.predict(X_test)

2/2 [==============================] - 0s 3ms/step


In [10]:
import numpy as np

y_pred = np.array([np.argmax(pred) for pred in predictions])

y_test_a = np.array([np.argmax(pred) for pred in y_test])



# assert y_test_a.shape == y_pred.shape
print(accuracy_score(y_test_a, y_pred))
print(recall_score(y_test_a, y_pred, average="weighted"))
print(precision_score(y_test_a, y_pred, average="weighted"))

0.8421052631578947
0.8421052631578947
0.9052631578947368


In [11]:
y_test_a

array([2, 0, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 0, 0, 0, 1, 2, 1, 0, 0, 1,
       2, 2, 2, 2, 2, 0, 0, 2, 1, 2, 0, 1, 2, 2, 1, 0])

In [12]:
y_pred

array([1, 0, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 0, 0, 0, 1, 2, 1, 0, 0, 1,
       1, 1, 1, 2, 2, 0, 0, 2, 1, 2, 0, 1, 2, 1, 1, 0])