In [1]:
import numpy as np

In [9]:
A = np.random.rand(1, 2)
A

array([[0.94165963, 0.01781984]])

In [8]:
B = np.random.rand(2, 1)
B

array([[0.0482358 ],
       [0.05264734]])

In [10]:
np.dot(A, B)

array([[0.04635987]])